/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Gradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test void lessThanTester() {
    	Library test = new Library();
    	int a=5, b=3;
    	assertTrue(test.lessThan(a, b), "Teste Quebrado, b>a");
    }
}
