/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Gradle;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public boolean lessThan(int a, int b)
    {
	    return a<b;
    }
}
